config/routes.rb
Rails.application.routes.draw do

  get 'thesis/new'

  get 'thesis/create'

  get 'thesis/update'

  get 'thesis/edit'

  get 'thesis/destroy'

  get 'thesis/index'

  get 'thesis/show'

  get 'rules/new'

  get 'rules/create'

  get 'rules/update'

  get 'rules/edit'

  get 'rules/destroy'

  get 'rules/index'

  get 'rules/show'

  resources :activities
  resources :teachers
  resources :students
  resources :rules
  resources :thesis

  get 'activities_category_student/:area', to: "activities#activities_category_student"
  get 'activities_all_student', to: "activities#activities_all_student"
  get 'show_answered_activity/:id/:category', to: "activities#show_answered_activity"
  post '/submit_answers', to: "activities#submit_answers"
  get 'answer_activity/:id_activity/:category', to: "activities#answer_activity"

  post '/thesis_modify_title', to: "thesis#modify_title"
  get 'update_title/:title_id/:title_counter', to: "thesis#update_title"
  get 'show_title/:title_id', to: "thesis#show_title"
  get 'register_title/:thesis_id', to: "thesis#register_title"
  get 'edit_title/:thesis_id', to: "thesis#edit_title"
  get 'register_approach/:thesis_id', to: "thesis#register_approach"
  get 'edit_approach/:thesis_id', to: "thesis#edit_approach"
  get 'register_general_purpose/:thesis_id', to: "thesis#register_general_purpose"
  get 'edit_general_purpose/:thesis_id', to: "thesis#edit_general_purpose"
  get 'register_specific_purposes/:thesis_id', to: "thesis#register_specific_purposes"
  get 'edit_specific_purposes/:thesis_id', to: "thesis#edit_specific_purposes"

  get 'edit_title_admin/:thesis_id', to: "thesis#edit_title_admin"
  get 'edit_approach_admin/:thesis_id', to: "thesis#edit_approach_admin"
  get 'edit_general_purpose_admin/:thesis_id', to: "thesis#edit_general_purpose_admin"
  get 'edit_specific_purposes_admin/:thesis_id', to: "thesis#edit_specific_purposes_admin"

  get 'show_title_admin/:title_id', to: "thesis#show_title_admin"
  get 'show_specific_admin/:version', to: "thesis#show_specific_admin"
  get 'show_approach_admin/:approach_id', to: "thesis#show_approach_admin"
  get 'show_general_purpose_admin/:general_purpose_id', to: "thesis#show_general_purpose_admin"


  get 'update_specific/:version/:specific_counter', to: "thesis#update_specific"
  post '/thesis_modify_specific', to: "thesis#modify_specific"
  post '/thesis_create_specific', to: "thesis#thesis_create_specific"
  get 'show_specific/:version', to: "thesis#show_specific"
  get 'register_repeat_specific_purposes/:thesis_id/:specific_specifics/:specific_counter', to: "thesis#register_repeat_specific_purposes"

  post '/thesis_create_title', to: "thesis#thesis_create_title"
  get 'register_repeat_title/:thesis_id/:title_content/:title_counter', to: "thesis#register_repeat_title"

  post '/thesis_modify_approach', to: "thesis#modify_approach"
  get 'update_approach/:approach_id/:approach_counter', to: "thesis#update_approach"
  get 'show_approach/:approach_id', to: "thesis#show_approach"
  post '/thesis_create_approach', to: "thesis#thesis_create_approach"
  get 'register_repeat_approach/:thesis_id/:approach_content/:approach_counter', to: "thesis#register_repeat_approach"

  post '/thesis_modify_general_purpose', to: "thesis#modify_general_purpose"
  get 'update_general_purpose/:general_purpose_id/:general_purpose_counter', to: "thesis#update_general_purpose"
  get 'show_general_purpose/:general_purpose_id', to: "thesis#show_general_purpose"
  post '/thesis_create_general_purpose', to: "thesis#thesis_create_general_purpose"
  get 'register_repeat_general_purpose/:thesis_id/:general_purpose_content/:general_purpose_counter', to: "thesis#register_repeat_general_purpose"

  get 'student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#student_request_thesis"
  get 'edit_student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#edit_student_request_thesis"
  get 'edit_thesis_teacher_select/:thesis_id', to: "thesis#edit_thesis_teacher_select"
  get 'thesis_teacher_select/:thesis_id', to: "thesis#thesis_teacher_select"
  get 'thesis_new_repeat_student/:titleCounter/:approachCounter/:generalCounter/:specificCounter', to: "thesis#thesis_new_repeat_student"
  get 'thesis_new_student', to: "thesis#thesis_new_student"
  post '/thesis_create_student', to: "thesis#thesis_create_student"
  get 'index_student', to: "thesis#index_student"
  get 'thesis_show_admin/:student_id', to: "thesis#show_admin"
  get 'thesis_show_section_admin/:section_id/:type', to: "thesis#show_section_admin"
  get 'rule_teacher/:id', to: "rules#rule_teacher"
  get 'rule_admin/:area', to: "rules#rule_admin"
  post '/update_rule_admin', to: "rules#update_rule_admin"
  get '/activities_admin/:id', to: "teachers#activities_admin"
  get '/activity_teacher_admin/:id/:origin', to: "teachers#activity_teacher_admin"
  get '/update_teacher_activity_admin/:id/:status/:origin', to: "teachers#update_teacher_activity_admin"

  get 'index_teacher', to: "activities#index_teacher"
  get 'new_teacher', to: "activities#new_teacher"
  post '/create_activity_teacher', to: "activities#create_activity_teacher"
  get 'destroy_activity_teacher/:id_activity', to: "activities#destroy_activity_teacher"
  get 'show_teacher_activity/:id_activity', to: "activities#show_teacher_activity"
  get 'edit_teacher_activity/:id_activity', to: "activities#edit_teacher_activity"
  post '/update_teacher_activity', to: "activities#update_teacher_activity"


  get 'index_teacher_rules', to: "rules#index_teacher_rules"
  get 'edit_rules_teacher/:area', to: "rules#edit_rules_teacher"
  post '/update_rule_teacher', to: "rules#update_rule_teacher"


  get '/internal_admin_information/:id', to: "internal#internal_admin_information"
  get '/internal_student_information/:id', to: "internal#internal_student_information"
  get '/internal_teacher_information/:id', to: "internal#internal_teacher_information"
  post '/update_admin', to: "internal#update_admin_attributes"
  post '/update_admin_password', to: "internal#update_admin_attributes_password"
  get '/update_admin', to: "internal#update_admin_attributes"
  get 'update_admin_password', to: "internal#update_admin_attributes_password"

  post '/update_student', to: "internal#update_student"
  post '/update_student_password', to: "internal#update_student_password"

  post '/update_teacher', to: "internal#update_teacher"
  post '/update_teacher_password', to: "internal#update_teacher_password"

  get 'list_students_requets', to: "teachers#list_students_requets"
  get 'show_student_thesis/:id_thesis', to: "thesis#show_student_thesis"

  get 'teacher_response_thesis/:id_thesis/:response', to: "thesis#teacher_response_thesis"
  get 'show_title_message/:id_title', to: "thesis#show_title_message"
  get 'show_approach_message/:id_approach', to: "thesis#show_approach_message"
  get 'show_general_purpose_message/:id_general_approach', to: "thesis#show_general_purpose_message"
  get 'show_specific_purposes_message/:version', to: "thesis#show_specific_purposes_message"

  get 'students_teacher_list', to: "students#students_teacher_list"
  get 'show_thesis_student/:id_student', to: "students#show_thesis_student"

  get 'show_title_detail/:id_thesis', to: "thesis#show_title_detail"
  get 'show_approach_detail/:id_thesis', to: "thesis#show_approach_detail"
  get 'show_general_purpose_detail/:id_thesis', to: "thesis#show_general_purpose_detail"
  get 'show_specific_purposes_detail/:id_thesis', to: "thesis#show_specific_purposes_detail"

  get 'show_title_teacher/:title_id', to: "thesis#show_title_teacher"
  get 'evaluate_title/:title_id', to: "thesis#evaluate_title"
  post '/title_teacher_evaluation', to: "thesis#title_teacher_evaluation"
  get 'confirm_title_teacher_evaluation/:title_id', to: "thesis#confirm_title_teacher_evaluation"
  post '/confirm_title_teacher_submit_evaluation', to: "thesis#confirm_title_teacher_submit_evaluation"

  get 'show_approach_teacher/:approach_id', to: "thesis#show_approach_teacher"
  get 'evaluate_approach/:approach_id', to: "thesis#evaluate_approach"
  post '/approach_teacher_evaluation', to: "thesis#approach_teacher_evaluation"
  get 'confirm_approach_teacher_evaluation/:approach_id', to: "thesis#confirm_approach_teacher_evaluation"
  post '/confirm_approach_teacher_submit_evaluation', to: "thesis#confirm_approach_teacher_submit_evaluation"

  get 'show_general_purpose_teacher/:general_purpose_id', to: "thesis#show_general_purpose_teacher"
  get 'evaluate_general_purpose/:general_purpose_id', to: "thesis#evaluate_general_purpose"
  post '/general_purpose_teacher_evaluation', to: "thesis#general_purpose_teacher_evaluation"
  get 'confirm_general_purpose_teacher_evaluation/:general_purpose_id', to: "thesis#confirm_general_purpose_teacher_evaluation"
  post '/confirm_general_purpose_teacher_submit_evaluation', to: "thesis#confirm_general_purpose_teacher_submit_evaluation"

  get 'show_specific_purpose_teacher/:version', to: "thesis#show_specific_purpose_teacher"
  get 'evaluate_specific_purpose/:version', to: "thesis#evaluate_specific_purpose"
  post '/specific_purpose_teacher_evaluation', to: "thesis#specific_purpose_teacher_evaluation"
  get 'confirm_specific_purpose_teacher_evaluation/:version', to: "thesis#confirm_specific_purpose_teacher_evaluation"
  post '/confirm_specific_purpose_teacher_submit_evaluation', to: "thesis#confirm_specific_purpose_teacher_submit_evaluation"


  root 'sessions#new'

  #sessions controller routes

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/unathorized', to: 'sessions#unathorized'
  post '/unathorized', to: 'sessions#unathorized'

  #password reset controller routes

  resources :password_resets, only: [:new, :create, :edit, :update]
  post '/password_resets/:id', to: 'password_resets#change_password'

app/models/teacher.rb
class Teacher < ApplicationRecord
  require 'securerandom'

  attr_accessor :remember_token, :activation_token, :reset_token

  enum nationality: [:Venezolano, :Extranjero]
  before_save {self.email = email.downcase}
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :identification_number, presence: true,
            uniqueness: {case_sensitive: false}

  def create_reset_digest
    self.reset_token = Teacher.new_token
    update_attribute(:reset_digest,  Teacher.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset_teacher(self).deliver_now
  end

  def Teacher.new_token
    SecureRandom.urlsafe_base64
  end

  def Teacher.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new

    @teacher = Teacher.new

  end

  def create

    @teacher = Teacher.new(teacher_params)
    if @teacher.save

      flash[:success] = "El profesor ha sido registrado"
      @teachers = Teacher.paginate(:page => params[:page], :per_page => 5)
      render 'index'

    else
      render 'new'
    end

  end

  def update

    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(teacher_edit_params)
      flash[:success] = "El profesor ha sido actualizado"
      @teachers = Teacher.paginate(:page => params[:page], :per_page => 5)
      render 'show'
    else
      render 'edit'
    end

  end


  def edit_student_request_thesis

    Message.where(id_thesis: params[:thesis_id]).destroy_all

    @message = Message.new
    @message.id_teacher = params[:teacher_id]
    @message.id_student = params[:student_id]
    @message.id_thesis = params[:thesis_id]

    if (@message.save)

      flash[:success] = "Su solicitud para el profesor ha sido enviada con éxito!"
      redirect_to(:action => 'index_student', :controller => "thesis") and return


    else

      flash[:danger] = "Su solicitud no ha podido ser enviada, por favor intente nuevamente!"
      redirect_to(:action => 'edit_thesis_teacher_select', :controller => "thesis", :thesis_id => params[:thesis_id]) and return

    end

  end

  def list_students_requets

    @messages = Message.where(id_teacher: session[:user_id]).paginate(:page => params[:page], :per_page => 5)
    @students = Array.new

    @messages.each do |message|

      @student = Student.find(message.id_student)
      @students.push(@student)

    end

  end


  def student_request_thesis

    @message = Message.new
    @message.id_teacher = params[:teacher_id]
    @message.id_student = params[:student_id]
    @message.id_thesis = params[:thesis_id]


    if (@message.save)

      flash[:success] = "Su solicitud para el profesor ha sido enviada con éxito!"
      redirect_to(:action => 'index_student', :controller => "thesis") and return


    else

      flash[:danger] = "Su solicitud no ha podido ser enviada, por favor intente nuevamente!"
      redirect_to(:action => 'thesis_teacher_select', :controller => "thesis", :thesis_id => params[:thesis_id]) and return

    end

  end


  def update_teacher_activity_admin

    if Activity.update(params[:id], status: params[:status])

      if params[:status] == "Aprobada"
        flash[:success] = "La actividad ha sido aprobada éxitosamente"
      else
        flash[:success] = "La actividad ha sido rechazada éxitosamente"
      end

      if params[:origin] == "0"

        @activity = Activity.find(params[:id])
        @activities = Activity.where(proposed_by: @activity.proposed_by, user_type: 2).paginate(:page => params[:page], :per_page => 5)

        render 'activities_admin'

      else

        @activities = Activity.paginate(:page => params[:page], :per_page => 5)
        @teachers = Teacher.all
        @admins = Admin.all

        redirect_to :action => 'index', :controller => "activities"

      end


    else

      flash[:danger] = 'No ha sido posible actualizar el estado de la actividad propuesta'

      if params[:origin] == "0"

        @activity = Activity.find(params[:id])
        @answers = Answer.where(activity_id: params[:id]).paginate(:page => params[:page], :per_page => 5)

        render 'activity_teacher_admin'

      else

        @activities = Activity.paginate(:page => params[:page], :per_page => 5)
        @teachers = Teacher.all
        @admins = Admin.all

        redirect_to :action => 'index', :controller => "activities"

      end

    end

  end


  def activity_teacher_admin

    @origin = params[:origin]
    @activity = Activity.find(params[:id])
    @answers = Answer.where(activity_id: params[:id]).paginate(:page => params[:page], :per_page => 5)

  end

  def activities_admin

    @activities = Activity.where(proposed_by: params[:id], user_type: 2).order(:area).paginate(:page => params[:page], :per_page => 5)

  end

  def edit

    @teacher = Teacher.find(params[:id])

  end

  def destroy

    Teacher.find(params[:id]).destroy
    flash[:success] = "El profesor ha sido eliminado"
    redirect_to teachers_url

  end

  def index

    @teachers = Teacher.paginate(:page => params[:page], :per_page => 5)

  end

  def show

    @teachers = Teacher.paginate(:page => params[:page], :per_page => 5)

  end

  def teacher_edit_params
    params.require(:teacher).permit(:first_name, :last_name, :email, :nationality, :identification_number)
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :email, :password, :nationality, :identification_number)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/activities_admin.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Actividades Propuestas por Profesor") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Actividades Propuestas por
  Profesor</h1>

<br><br>

<% if @activities.size == 0 %>

  <h1>Este profesor aún no posee actividades propuestas</h1>

<% else %>

  <%= will_paginate @activities %>

  <table>

    <tr style="border: black 2px solid; height: 40px;">
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Área</b></th>
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Título</b></th>
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Estado</b></th>
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
    </tr>
    <% @activities.each do |activity| %>

      <%= @value = "" %>

      <% if activity.area == "Titulo"
           @value = "Título"
         elsif activity.area == "Planteamiento"
           @value = "Planteamiento del Problema"
         elsif activity.area == "Obj_General"
           @value = "Objetivo General"
         else
           @value = "Objetivos Específicos"
         end %>

      <tr style="border: black 2px solid; height: 40px;text-align: center;">
        <td style="border: black 1px solid"><%= @value %> </td>
        <td style="border: black 1px solid"> <%= activity.title %> </td>
        <td style="border: black 1px solid"> <%= activity.status %> </td>
        <td style="border: black 1px solid"> <%= link_to "Consultar", {:controller => :teachers, :action => :activity_teacher_admin, :id => activity.id, :origin => 0}, {:class => 'btn btn-info', :style => 'width:100px;'} %> </td>
      </tr>


    <% end %>

  </table>

<% end %>


<%= will_paginate @activities %>

app/views/teachers/activity_teacher_admin.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<% provide(:title, "Actividad Propuesta por Profesor") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Actividad Propuesta por
  Profesor</h1>


<%= render 'shared/error_activity_messages' %>

<table>

  <tr style="height: 40px">
    <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Área</b></td>

    <%= @value = "" %>

    <% if @activity.area == "Titulo"
         @value = "Título"
       elsif @activity.area == "Planteamiento"
         @value = "Planteamiento del Problema"
       elsif @activity.area == "Obj_General"
         @value = "Objetivo General"
       else
         @value = "Objetivos Específicos"
       end %>

    <td><%= @value %> </td>
  </tr>

  <tr style="height: 40px">
    <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Título</b></td>
    <td><%= @activity.title %></td>
  </tr>

  <tr style="height: 40px">
    <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Descripción</b></td>
    <td><%= @activity.description %></td>
  </tr>

  <tr style="height: 40px">
    <td><h3 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Respuestas</h3></td>
  </tr>

</table>

<%= will_paginate @answers %>

<table border="1">
  <tr style="border: black 2px solid; height: 40px;">
    <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Respuesta</b></td>
    <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Correcta</b></td>
    <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff"># Respondida Correcta</b></td>
    <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff"># Respondida Incorrecta</b></td>
  </tr>
  <% @answers.each do |answer| %>
    <tr style="border: black 2px solid; height: 40px;text-align: center;">
      <td style="border: black 1px solid"><%= answer.text %></td>
      <td style="border: black 1px solid">
        <%= answer.correct %>
      </td>

      <td style="text-align: center;">

        <% if answer.correct_total.nil? %>

          0

        <% else %>

          <%= answer.correct_total %>


        <% end %>


      </td>

      <td style="text-align: center;">

        <% if answer.wrong_total.nil? %>

          0

        <% else %>

          <%= answer.wrong_total %>


        <% end %>


      </td>

    </tr>
  <% end %>
</table>

<br>

<%= link_to "Aprobar Actividad", {:controller => :teachers, :action => :update_teacher_activity_admin, :id => @activity.id, :status => "Aprobada", :origin => @origin}, {:class => 'btn btn-success', :style => 'width:200px;'} %>

<br><br>

<%= link_to "Rechazar Actividad", {:controller => :teachers, :action => :update_teacher_activity_admin, :id => @activity.id, :status => "Rechazada", :origin => @origin}, {:class => 'btn btn-danger', :style => 'width:200px;'} %>

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/destroy.html.erb
<h1>Teachers#destroy</h1>
<p>Find me in app/views/teachers/destroy.html.erb</p>

app/views/teachers/edit.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Profesores") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Consultar Profesor</h1>


<%= form_for @teacher do |f| %>

  <%= render 'shared/error_messages' %>

  <table>
    <tr style="height: 40px">
      <td><%= f.label "Nombre" %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.label "Apellido" %></td>
      <td><%= f.text_field :last_name %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.label "Correo Electrónico" %></td>
      <td><%= f.text_field :email %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.label "Cédula de Identidad" %></td>
      <td><%= f.select(:nationality, options_for_select([['Venezolano', 'Venezolano'], ['Extranjero', 'Extranjero']], :selected => @teacher.nationality)) %> </td>
      <td><%= f.text_field :identification_number %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.submit "Actualizar Profesor", class: "btn btn-info", :style => 'width:200px;' %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= link_to "Consultar Actividades", {:controller => :teachers, :action => :activities_admin, :id => @teacher.id}, {:class => 'btn btn-primary', :style => 'width:200px;'} %></td>
    </tr>

  </table>
<% end %>

app/views/teachers/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Profesores") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Profesores</h1>

<%= link_to "Registrar Profesor", {:controller => :teachers, :action => :new}, {:class => 'btn btn-success'} %>
<br><br>

<%= will_paginate @teachers %>

<table>

  <tr style="border: black 2px solid; height: 40px;">
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Profesor</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Cédula de Identidad</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
  </tr>
  <% @teachers.each do |teacher| %>
    <tr style="border: black 2px solid; height: 40px;text-align: center;">
      <td style="border: black 1px solid"><%= teacher.first_name %> <%= teacher.last_name %></td>
      <td style="border: black 1px solid"> <%= teacher.nationality %> - <%= teacher.identification_number %> </td>
      <td style="border: black 1px solid"> <%= link_to "Eliminar", teacher, method: :delete,
                                                       data: {confirm: "Confirma que desea eliminar este profesor?"}, :class => 'btn btn-danger' %> </td>
      <td style="border: black 1px solid"> <%= link_to 'Consultar', edit_teacher_path(teacher), :class => 'btn btn-info' %> </td>
    </tr>


  <% end %>

</table>


<%= will_paginate @teachers %>

app/views/teachers/show.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Profesores") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Profesores</h1>

<%= link_to "Registrar Profesor", {:controller => :teachers, :action => :new}, {:class => 'btn btn-success'} %>
<br><br>

<%= will_paginate @teachers %>

<table>

  <tr style="border: black 2px solid; height: 40px;">
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Profesor</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Cédula de Identidad</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
  </tr>
  <% @teachers.each do |teacher| %>
    <tr style="border: black 2px solid; height: 40px;text-align: center;">
      <td style="border: black 1px solid"><%= teacher.first_name %> <%= teacher.last_name %></td>
      <td style="border: black 1px solid"> <%= teacher.nationality %> - <%= teacher.identification_number %> </td>
      <td style="border: black 1px solid"> <%= link_to "Eliminar", teacher, method: :delete,
                                                       data: {confirm: "Confirma que desea eliminar este profesor?"}, :class => 'btn btn-danger' %> </td>
      <td style="border: black 1px solid"> <%= link_to 'Consultar', edit_teacher_path(teacher), :class => 'btn btn-info' %> </td>
    </tr>


  <% end %>

</table>


<%= will_paginate @teachers %>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>