config/routes.rb
Rails.application.routes.draw do

  get 'thesis/new'

  get 'thesis/create'

  get 'thesis/update'

  get 'thesis/edit'

  get 'thesis/destroy'

  get 'thesis/index'

  get 'thesis/show'

  get 'rules/new'

  get 'rules/create'

  get 'rules/update'

  get 'rules/edit'

  get 'rules/destroy'

  get 'rules/index'

  get 'rules/show'

  resources :activities
  resources :teachers
  resources :students
  resources :rules
  resources :thesis

  get 'activities_category_student/:area', to: "activities#activities_category_student"
  get 'activities_all_student', to: "activities#activities_all_student"
  get 'show_answered_activity/:id/:category', to: "activities#show_answered_activity"
  post '/submit_answers', to: "activities#submit_answers"
  get 'answer_activity/:id_activity/:category', to: "activities#answer_activity"

  post '/thesis_modify_title', to: "thesis#modify_title"
  get 'update_title/:title_id/:title_counter', to: "thesis#update_title"
  get 'show_title/:title_id', to: "thesis#show_title"
  get 'register_title/:thesis_id', to: "thesis#register_title"
  get 'edit_title/:thesis_id', to: "thesis#edit_title"
  get 'register_approach/:thesis_id', to: "thesis#register_approach"
  get 'edit_approach/:thesis_id', to: "thesis#edit_approach"
  get 'register_general_purpose/:thesis_id', to: "thesis#register_general_purpose"
  get 'edit_general_purpose/:thesis_id', to: "thesis#edit_general_purpose"
  get 'register_specific_purposes/:thesis_id', to: "thesis#register_specific_purposes"
  get 'edit_specific_purposes/:thesis_id', to: "thesis#edit_specific_purposes"

  get 'edit_title_admin/:thesis_id', to: "thesis#edit_title_admin"
  get 'edit_approach_admin/:thesis_id', to: "thesis#edit_approach_admin"
  get 'edit_general_purpose_admin/:thesis_id', to: "thesis#edit_general_purpose_admin"
  get 'edit_specific_purposes_admin/:thesis_id', to: "thesis#edit_specific_purposes_admin"

  get 'show_title_admin/:title_id', to: "thesis#show_title_admin"
  get 'show_specific_admin/:version', to: "thesis#show_specific_admin"
  get 'show_approach_admin/:approach_id', to: "thesis#show_approach_admin"
  get 'show_general_purpose_admin/:general_purpose_id', to: "thesis#show_general_purpose_admin"


  get 'update_specific/:version/:specific_counter', to: "thesis#update_specific"
  post '/thesis_modify_specific', to: "thesis#modify_specific"
  post '/thesis_create_specific', to: "thesis#thesis_create_specific"
  get 'show_specific/:version', to: "thesis#show_specific"
  get 'register_repeat_specific_purposes/:thesis_id/:specific_specifics/:specific_counter', to: "thesis#register_repeat_specific_purposes"

  post '/thesis_create_title', to: "thesis#thesis_create_title"
  get 'register_repeat_title/:thesis_id/:title_content/:title_counter', to: "thesis#register_repeat_title"

  post '/thesis_modify_approach', to: "thesis#modify_approach"
  get 'update_approach/:approach_id/:approach_counter', to: "thesis#update_approach"
  get 'show_approach/:approach_id', to: "thesis#show_approach"
  post '/thesis_create_approach', to: "thesis#thesis_create_approach"
  get 'register_repeat_approach/:thesis_id/:approach_content/:approach_counter', to: "thesis#register_repeat_approach"

  post '/thesis_modify_general_purpose', to: "thesis#modify_general_purpose"
  get 'update_general_purpose/:general_purpose_id/:general_purpose_counter', to: "thesis#update_general_purpose"
  get 'show_general_purpose/:general_purpose_id', to: "thesis#show_general_purpose"
  post '/thesis_create_general_purpose', to: "thesis#thesis_create_general_purpose"
  get 'register_repeat_general_purpose/:thesis_id/:general_purpose_content/:general_purpose_counter', to: "thesis#register_repeat_general_purpose"

  get 'student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#student_request_thesis"
  get 'edit_student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#edit_student_request_thesis"
  get 'edit_thesis_teacher_select/:thesis_id', to: "thesis#edit_thesis_teacher_select"
  get 'thesis_teacher_select/:thesis_id', to: "thesis#thesis_teacher_select"
  get 'thesis_new_repeat_student/:titleCounter/:approachCounter/:generalCounter/:specificCounter', to: "thesis#thesis_new_repeat_student"
  get 'thesis_new_student', to: "thesis#thesis_new_student"
  post '/thesis_create_student', to: "thesis#thesis_create_student"
  get 'index_student', to: "thesis#index_student"
  get 'thesis_show_admin/:student_id', to: "thesis#show_admin"
  get 'thesis_show_section_admin/:section_id/:type', to: "thesis#show_section_admin"
  get 'rule_teacher/:id', to: "rules#rule_teacher"
  get 'rule_admin/:area', to: "rules#rule_admin"
  post '/update_rule_admin', to: "rules#update_rule_admin"
  get '/activities_admin/:id', to: "teachers#activities_admin"
  get '/activity_teacher_admin/:id/:origin', to: "teachers#activity_teacher_admin"
  get '/update_teacher_activity_admin/:id/:status/:origin', to: "teachers#update_teacher_activity_admin"

  get 'index_teacher', to: "activities#index_teacher"
  get 'new_teacher', to: "activities#new_teacher"
  post '/create_activity_teacher', to: "activities#create_activity_teacher"
  get 'destroy_activity_teacher/:id_activity', to: "activities#destroy_activity_teacher"
  get 'show_teacher_activity/:id_activity', to: "activities#show_teacher_activity"
  get 'edit_teacher_activity/:id_activity', to: "activities#edit_teacher_activity"
  post '/update_teacher_activity', to: "activities#update_teacher_activity"


  get 'index_teacher_rules', to: "rules#index_teacher_rules"
  get 'edit_rules_teacher/:area', to: "rules#edit_rules_teacher"
  post '/update_rule_teacher', to: "rules#update_rule_teacher"


  get '/internal_admin_information/:id', to: "internal#internal_admin_information"
  get '/internal_student_information/:id', to: "internal#internal_student_information"
  get '/internal_teacher_information/:id', to: "internal#internal_teacher_information"
  post '/update_admin', to: "internal#update_admin_attributes"
  post '/update_admin_password', to: "internal#update_admin_attributes_password"
  get '/update_admin', to: "internal#update_admin_attributes"
  get 'update_admin_password', to: "internal#update_admin_attributes_password"

  post '/update_student', to: "internal#update_student"
  post '/update_student_password', to: "internal#update_student_password"

  post '/update_teacher', to: "internal#update_teacher"
  post '/update_teacher_password', to: "internal#update_teacher_password"

  get 'list_students_requets', to: "teachers#list_students_requets"
  get 'show_student_thesis/:id_thesis', to: "thesis#show_student_thesis"

  get 'teacher_response_thesis/:id_thesis/:response', to: "thesis#teacher_response_thesis"
  get 'show_title_message/:id_title', to: "thesis#show_title_message"
  get 'show_approach_message/:id_approach', to: "thesis#show_approach_message"
  get 'show_general_purpose_message/:id_general_approach', to: "thesis#show_general_purpose_message"
  get 'show_specific_purposes_message/:version', to: "thesis#show_specific_purposes_message"

  get 'students_teacher_list', to: "students#students_teacher_list"
  get 'show_thesis_student/:id_student', to: "students#show_thesis_student"

  get 'show_title_detail/:id_thesis', to: "thesis#show_title_detail"
  get 'show_approach_detail/:id_thesis', to: "thesis#show_approach_detail"
  get 'show_general_purpose_detail/:id_thesis', to: "thesis#show_general_purpose_detail"
  get 'show_specific_purposes_detail/:id_thesis', to: "thesis#show_specific_purposes_detail"

  get 'show_title_teacher/:title_id', to: "thesis#show_title_teacher"
  get 'evaluate_title/:title_id', to: "thesis#evaluate_title"
  post '/title_teacher_evaluation', to: "thesis#title_teacher_evaluation"
  get 'confirm_title_teacher_evaluation/:title_id', to: "thesis#confirm_title_teacher_evaluation"
  post '/confirm_title_teacher_submit_evaluation', to: "thesis#confirm_title_teacher_submit_evaluation"

  get 'show_approach_teacher/:approach_id', to: "thesis#show_approach_teacher"
  get 'evaluate_approach/:approach_id', to: "thesis#evaluate_approach"
  post '/approach_teacher_evaluation', to: "thesis#approach_teacher_evaluation"
  get 'confirm_approach_teacher_evaluation/:approach_id', to: "thesis#confirm_approach_teacher_evaluation"
  post '/confirm_approach_teacher_submit_evaluation', to: "thesis#confirm_approach_teacher_submit_evaluation"

  get 'show_general_purpose_teacher/:general_purpose_id', to: "thesis#show_general_purpose_teacher"
  get 'evaluate_general_purpose/:general_purpose_id', to: "thesis#evaluate_general_purpose"
  post '/general_purpose_teacher_evaluation', to: "thesis#general_purpose_teacher_evaluation"
  get 'confirm_general_purpose_teacher_evaluation/:general_purpose_id', to: "thesis#confirm_general_purpose_teacher_evaluation"
  post '/confirm_general_purpose_teacher_submit_evaluation', to: "thesis#confirm_general_purpose_teacher_submit_evaluation"

  get 'show_specific_purpose_teacher/:version', to: "thesis#show_specific_purpose_teacher"
  get 'evaluate_specific_purpose/:version', to: "thesis#evaluate_specific_purpose"
  post '/specific_purpose_teacher_evaluation', to: "thesis#specific_purpose_teacher_evaluation"
  get 'confirm_specific_purpose_teacher_evaluation/:version', to: "thesis#confirm_specific_purpose_teacher_evaluation"
  post '/confirm_specific_purpose_teacher_submit_evaluation', to: "thesis#confirm_specific_purpose_teacher_submit_evaluation"


  root 'sessions#new'

  #sessions controller routes

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/unathorized', to: 'sessions#unathorized'
  post '/unathorized', to: 'sessions#unathorized'

  #password reset controller routes

  resources :password_resets, only: [:new, :create, :edit, :update]
  post '/password_resets/:id', to: 'password_resets#change_password'

app/models/activity.rb
class Activity < ApplicationRecord



  enum area: [:Titulo, :Planteamiento, :Obj_General, :Obj_Especifico]
  enum status: [:Aprobada, :Pendiente, :Rechazada]

  validates :title, presence: true
  validates :description, presence: true

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/answer_activity.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<script>

    function unCheckAnother(row, select) {

        var i = row.parentNode.parentNode.rowIndex;
        var yesIndex = "checkBoxYes_" + i
        var noIndex = "checkBoxNo_" + i

        var si = document.getElementById(yesIndex)
        var no = document.getElementById(noIndex)

        if (parseInt(select) == 0) {

            if (no.checked) {

                no.checked = false;

            }

        } else {

            if (si.checked) {

                si.checked = false;
            }
        }

        var len = document.getElementById("activity_counterAnswers").value
        var realIndex = (parseInt(i) - 1)
        var result = ""

        for (var index = 0; index <= (parseInt(len) - 1); index++) {

            var yesIndexFor = "checkBoxYes_" + (index + 1)
            var noIndexFor = "checkBoxNo_" + (index + 1)

            if (document.getElementById(yesIndexFor).checked) {

                if (result == "") {

                    result = "Si"

                } else {

                    result = result + "*Si"

                }

            } else {

                if (result == "") {

                    result = "No"

                } else {

                    result = result + "*No"

                }


            }


        }

        document.getElementById("activity_userAnswers").value = result


    }

</script>

<% provide(:title, "Actividad Propuesta") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Actividad Propuesta</h1>

<%= form_for(:activity, url: submit_answers_path) do |f| %>

  <table>

    <tr style="height: 40px">
      <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Área</b></td>

      <%= @value = "" %>

      <% if @activity.area == "Titulo"
           @value = "Título"
         elsif @activity.area == "Planteamiento"
           @value = "Planteamiento del Problema"
         elsif @activity.area == "Obj_General"
           @value = "Objetivo General"
         else
           @value = "Objetivos Específicos"
         end %>

      <td><%= @value %> </td>
    </tr>

    <tr style="height: 40px">
      <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Título</b></td>
      <td><%= @activity.title %></td>
    </tr>

    <tr style="height: 40px">
      <td style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;"><b>Descripción</b></td>
      <td><%= @activity.description %></td>
    </tr>

    <tr style="height: 40px">
      <td><h3 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Opciones</h3></td>
    </tr>

  </table>


  <table id="RespuestasTabla">
    <tr style="border: black 2px solid; height: 40px;">
      <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Opción</b></td>
      <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Correcta</b></td>
      <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Incorrecta</b></td>
    </tr>
    <% @index = 1 %>
    <% @answersLoop = "" %>
    <% @answers.each do |answer| %>

      <% if @answersLoop == ""

           @answersLoop = "No"

         else

           @answersLoop = @answersLoop + "*No"

         end %>


      <tr style="border: black 2px solid; height: 40px;text-align: center;">
        <td style="border: black 1px solid"><%= answer.text %></td>
        <td style="border: black 1px solid">
          <input id="<%= "checkBoxYes_" + @index.to_s %>" type="checkbox" onclick="unCheckAnother(this,0);">
        </td>
        <td style="border: black 1px solid">
          <input id="<%= "checkBoxNo_" + @index.to_s %>" type="checkbox" onclick="unCheckAnother(this,1);">
        </td>

      </tr>

      <% @index = @index + 1 %>

    <% end %>

    <%= f.hidden_field :counterAnswers, :value => @answers.count %>
    <%= f.hidden_field :userAnswers, :value => @answersLoop %>
    <%= f.hidden_field :id, :value => @activity.id %>
    <%= f.hidden_field :origin, :value => @origin %>

    <tr style="height: 40px">
      <td><%= f.submit "Enviar Respuestas", class: "btn btn-success" %></td>
    </tr>
    <% if @origin == 10 %>
      <tr style="height: 40px">
        <td>
          <%= link_to "Regresar", {:controller => :activities, :action => :activities_all_student}, {:class => 'btn btn-info'} %>
        </td>
      </tr>
    <% else %>
      <tr style="height: 40px">
        <td>
          <%= link_to "Regresar", {:controller => :activities, :action => :activities_category_student, :area => @origin}, {:class => 'btn btn-info'} %>
        </td>
      </tr>
    <% end %>

  </table>

<% end %>

<br>

app/views/activities/create.html.erb
<h1>Activities#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/activities/destroy.html.erb
<h1>Activities#destroy</h1>
<p>Find me in app/views/activities/destroy.html.erb</p>

app/views/activities/edit_teacher_activity.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<script>

    function deleteRow(row) {

        var value = parseInt(document.getElementById('answer_counter').value);

        if ((value == 0) || (value == 1)) {

            alert("Debe tener al menos una respuesta");

        } else {

            var i = row.parentNode.parentNode.rowIndex;
            document.getElementById('RespuestasTabla').deleteRow(i);

            value = value - 1;
            document.getElementById('answer_counter').value = value

            var x = document.getElementById('RespuestasTabla');
            var len = x.rows.length;

            document.getElementById('activity_answers').value = ""

            for (var index = 1; index <= len; index++) {

                var row = x.rows[index]

                if (document.getElementById('activity_answers').value == "") {

                    document.getElementById('activity_answers').value = row.cells[0].getElementsByTagName('input')[0].value + "%" + row.cells[1].getElementsByTagName('input')[0].value + "%" + row.cells[2].getElementsByTagName('input')[0].value + "%" + row.cells[3].getElementsByTagName('input')[0].value

                } else {

                    document.getElementById('activity_answers').value = document.getElementById('activity_answers').value + "*" + row.cells[0].getElementsByTagName('input')[0].value + "%" + row.cells[1].getElementsByTagName('input')[0].value +  "%" + row.cells[2].getElementsByTagName('input')[0].value + "%" + row.cells[3].getElementsByTagName('input')[0].value

                }


            }

        }


    }


    function insRow(respuesta, correcta) {

        var x = document.getElementById('RespuestasTabla');
        var value = parseInt(document.getElementById('answer_counter').value);

        if (respuesta != "") {


            var new_row = x.rows[1].cloneNode(true);
            var len = x.rows.length;

            var inp1 = new_row.cells[0].getElementsByTagName('input')[0];
            inp1.id += len;
            inp1.value = respuesta;
            var inp2 = new_row.cells[1].getElementsByTagName('input')[0];
            inp2.id += len;
            inp2.value = correcta;


            var inp3 = new_row.cells[2].getElementsByTagName('input')[0];
            inp3.id += len;
            inp3.value = 0;
            var inp4 = new_row.cells[3].getElementsByTagName('input')[0];
            inp4.id += len;
            inp4.value = 0;

            x.appendChild(new_row);

            if (value == 0) {
                document.getElementById('RespuestasTabla').deleteRow(1);

            }

            document.getElementById('answer_text').value = ""
            document.getElementById('answer_correct').value = "Si"

            if (document.getElementById('activity_answers').value == "") {

                document.getElementById('activity_answers').value = respuesta + "%" + correcta + "%0%0";

            } else {

                document.getElementById('activity_answers').value = document.getElementById('activity_answers').value + "*" + respuesta + "%" + correcta + "%0%0";

            }

            value = value + 1;
            document.getElementById('answer_counter').value = value

        } else {

            alert("Debe introducir un texto para la respuesta");

        }


    }

</script>


<% provide(:title, "Actividades") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Editar Actividad</h1>


<%= form_for(:activity, url: update_teacher_activity_path) do |f| %>

  <%= render 'shared/error_activity_messages' %>

  <table>

    <tr style="height: 40px">
      <td><%= f.label "Área" %></td>
      <td><%= f.select(:area, options_for_select([['Título', 'Titulo'], ['Planteamiento del Problema', 'Planteamiento'], ['Objetivo General', 'Obj_General'], ['Objetivos Específicos', 'Obj_Especifico']], :selected => @activity.area)) %> </td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.label "Título" %></td>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr style="height: 40px">
      <td><%= f.label "Descripción" %></td>
      <td><%= f.text_area(:description, size: '40x10') %></td>
    </tr>

    <tr style="height: 40px">
      <td><h3>Respuestas</h3></td>
    </tr>


    <tr style="height: 40px">
      <td><label>Respuesta</label></td>
      <td><input type="text" name="answer[text]" id="answer_text"></td>
    </tr>

    <tr style="height: 40px">
      <td><label>Correcta</label></td>
      <td>
        <select name="answer[correct]" id="answer_correct">
          <option value="Si">Si</option>
          <option value="No">No</option>
        </select>
      </td>
    </tr>

    <tr style="height: 40px">
      <td>
        <input value="Agregar Respuesta" class="btn btn-info" data-disable-with="Agregar Respuesta" onclick="insRow(document.getElementById('answer_text').value,document.getElementById('answer_correct').value)">
      </td>
    </tr>

    <%= f.hidden_field :proposed_by, :value => session[:user_id] %>
    <%= f.hidden_field :user_type, :value => 2 %>
    <%= f.hidden_field :id, :value => @activity.id %>
    <%= f.hidden_field :status, :value => "Pendiente" %>


    <% if (@answers.count == 0) %>

      <%= f.hidden_field :answers, :value => "" %>
      <input type="hidden" name="answer[counter]" id="answer_counter" value="0">

    <% else %>

      <input type="hidden" name="answer[counter]" id="answer_counter" value="<%= @answers.count %>">
      <%= f.hidden_field :answers, :value => @answersString %>


    <% end %>


    <tr>
      <table id="RespuestasTabla" border="1">
        <tr style="border: black 2px solid; height: 40px;">
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff">Respuesta</b></td>
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff">Correcta</b></td>
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff"># Respondida Correcta</b></td>
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff"># Respondida Incorrecta</b></td>
        </tr>
        <% if @answers.count == 0 %>
          <tr style="border: black 2px solid; height: 40px;">
            <td><input size=25 type="text" id="latbox"/></td>
            <td><input size=25 type="text" id="lngbox"/></td>
            <td>
              <input type="button" id="delPOIbutton" value="Eliminar" class="btn btn-danger" onclick="deleteRow(this)"/>
            </td>
          </tr>
        <% else %>
          <% @answerEach = @answersString.split("*") %>
          <% @answerEach.each do |answerDo| %>
            <% answerElement = answerDo.split("%") %>
            <tr style="border: black 2px solid; height: 40px;">
              <td><input size=25 type="text" id="latbox" value="<%= answerElement[0] %>"/></td>
              <td><input size=25 type="text" id="latbox" value="<%= answerElement[1] %>"/></td>
              <td><input size=25 type="text" id="latbox" value="<%= answerElement[2] %>"/></td>
              <td><input size=25 type="text" id="latbox" value="<%= answerElement[3] %>"/></td>
              <td>
                <input type="button" id="delPOIbutton" value="Eliminar" class="btn btn-danger" onclick="deleteRow(this)"/>
              </td>
            </tr>
          <% end %>
        <% end %>


      </table>
    </tr>

    <tr><br></tr>

    <tr style="height: 40px">
      <td><%= f.submit "Actualizar Actividad", class: "btn btn-info" %></td>
    </tr>

  </table>
<% end %>

app/views/activities/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Actividades") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Actividades</h1>

<%= link_to "Registrar Nueva Actividad", {:controller => :activities, :action => :new}, {:class => 'btn btn-success'} %>
<br><br>

<%= will_paginate @activities %>

<table>

  <tr style="border: black 2px solid; height: 40px;">
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Área</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Título</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Estado</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Propuesta por</b></th>
    <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
  </tr>
  <% @activities.each do |activity| %>

    <%= @value = "" %>

    <% if activity.area == "Titulo"
         @value = "Título"
       elsif activity.area == "Planteamiento"
         @value = "Planteamiento del Problema"
       elsif activity.area == "Obj_General"
         @value = "Objetivo General"
       else
         @value = "Objetivos Específicos"
       end %>

    <tr style="border: black 2px solid; height: 40px;text-align: center;">
      <td style="border: black 1px solid"><%= @value %> </td>
      <td style="border: black 1px solid"> <%= activity.title %> </td>
      <td style="border: black 1px solid"> <%= activity.status %> </td>
      <% if activity.user_type == 2 %>

        <% @teachers.each do |teacher| %>

          <% if activity.proposed_by == teacher.id %>

            <td style="border: black 1px solid"> <%= teacher.first_name %> <%= teacher.last_name %></td>
            <td style="border: black 1px solid"><%= link_to "Consultar", {:controller => :teachers, :action => :activity_teacher_admin, :id => activity.id, :origin => 1}, {:class => 'btn btn-info', :style => 'width:100px;'} %></td>

            <% break %>

          <% end %>

        <% end %>

      <% else %>

        <% @admins.each do |admin| %>

          <% if activity.proposed_by == admin.id %>

            <td style="border: black 1px solid"> <%= admin.email %> </td>

            <% if admin.id == session[:user_id] %>

              <td style="border: black 1px solid"> <%= link_to 'Editar', edit_activity_path(activity), {:class => 'btn btn-danger', :style => 'width:100px;'} %> </td>

            <% else %>

              <td style="border: black 1px solid"><%= link_to "Consultar", {:controller => :teachers, :action => :activity_teacher_admin, :id => activity.id, :origin => 1}, {:class => 'btn btn-info', :style => 'width:100px;'} %></td>

            <% end %>


            <% break %>

          <% end %>

        <% end %>

      <% end %>


    </tr>


  <% end %>

</table>


<%= will_paginate @activities %>

app/views/activities/show.html.erb
<h1>Activities#show</h1>
<p>Find me in app/views/activities/show.html.erb</p>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>