config/routes.rb
Rails.application.routes.draw do

  get 'thesis/new'

  get 'thesis/create'

  get 'thesis/update'

  get 'thesis/edit'

  get 'thesis/destroy'

  get 'thesis/index'

  get 'thesis/show'

  get 'rules/new'

  get 'rules/create'

  get 'rules/update'

  get 'rules/edit'

  get 'rules/destroy'

  get 'rules/index'

  get 'rules/show'

  resources :activities
  resources :teachers
  resources :students
  resources :rules
  resources :thesis

  get 'activities_category_student/:area', to: "activities#activities_category_student"
  get 'activities_all_student', to: "activities#activities_all_student"
  get 'show_answered_activity/:id/:category', to: "activities#show_answered_activity"
  post '/submit_answers', to: "activities#submit_answers"
  get 'answer_activity/:id_activity/:category', to: "activities#answer_activity"

  post '/thesis_modify_title', to: "thesis#modify_title"
  get 'update_title/:title_id/:title_counter', to: "thesis#update_title"
  get 'show_title/:title_id', to: "thesis#show_title"
  get 'register_title/:thesis_id', to: "thesis#register_title"
  get 'edit_title/:thesis_id', to: "thesis#edit_title"
  get 'register_approach/:thesis_id', to: "thesis#register_approach"
  get 'edit_approach/:thesis_id', to: "thesis#edit_approach"
  get 'register_general_purpose/:thesis_id', to: "thesis#register_general_purpose"
  get 'edit_general_purpose/:thesis_id', to: "thesis#edit_general_purpose"
  get 'register_specific_purposes/:thesis_id', to: "thesis#register_specific_purposes"
  get 'edit_specific_purposes/:thesis_id', to: "thesis#edit_specific_purposes"

  get 'edit_title_admin/:thesis_id', to: "thesis#edit_title_admin"
  get 'edit_approach_admin/:thesis_id', to: "thesis#edit_approach_admin"
  get 'edit_general_purpose_admin/:thesis_id', to: "thesis#edit_general_purpose_admin"
  get 'edit_specific_purposes_admin/:thesis_id', to: "thesis#edit_specific_purposes_admin"

  get 'show_title_admin/:title_id', to: "thesis#show_title_admin"
  get 'show_specific_admin/:version', to: "thesis#show_specific_admin"
  get 'show_approach_admin/:approach_id', to: "thesis#show_approach_admin"
  get 'show_general_purpose_admin/:general_purpose_id', to: "thesis#show_general_purpose_admin"


  get 'update_specific/:version/:specific_counter', to: "thesis#update_specific"
  post '/thesis_modify_specific', to: "thesis#modify_specific"
  post '/thesis_create_specific', to: "thesis#thesis_create_specific"
  get 'show_specific/:version', to: "thesis#show_specific"
  get 'register_repeat_specific_purposes/:thesis_id/:specific_specifics/:specific_counter', to: "thesis#register_repeat_specific_purposes"

  post '/thesis_create_title', to: "thesis#thesis_create_title"
  get 'register_repeat_title/:thesis_id/:title_content/:title_counter', to: "thesis#register_repeat_title"

  post '/thesis_modify_approach', to: "thesis#modify_approach"
  get 'update_approach/:approach_id/:approach_counter', to: "thesis#update_approach"
  get 'show_approach/:approach_id', to: "thesis#show_approach"
  post '/thesis_create_approach', to: "thesis#thesis_create_approach"
  get 'register_repeat_approach/:thesis_id/:approach_content/:approach_counter', to: "thesis#register_repeat_approach"

  post '/thesis_modify_general_purpose', to: "thesis#modify_general_purpose"
  get 'update_general_purpose/:general_purpose_id/:general_purpose_counter', to: "thesis#update_general_purpose"
  get 'show_general_purpose/:general_purpose_id', to: "thesis#show_general_purpose"
  post '/thesis_create_general_purpose', to: "thesis#thesis_create_general_purpose"
  get 'register_repeat_general_purpose/:thesis_id/:general_purpose_content/:general_purpose_counter', to: "thesis#register_repeat_general_purpose"

  get 'student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#student_request_thesis"
  get 'edit_student_request_thesis/:teacher_id/:thesis_id/:student_id', to: "teachers#edit_student_request_thesis"
  get 'edit_thesis_teacher_select/:thesis_id', to: "thesis#edit_thesis_teacher_select"
  get 'thesis_teacher_select/:thesis_id', to: "thesis#thesis_teacher_select"
  get 'thesis_new_repeat_student/:titleCounter/:approachCounter/:generalCounter/:specificCounter', to: "thesis#thesis_new_repeat_student"
  get 'thesis_new_student', to: "thesis#thesis_new_student"
  post '/thesis_create_student', to: "thesis#thesis_create_student"
  get 'index_student', to: "thesis#index_student"
  get 'thesis_show_admin/:student_id', to: "thesis#show_admin"
  get 'thesis_show_section_admin/:section_id/:type', to: "thesis#show_section_admin"
  get 'rule_teacher/:id', to: "rules#rule_teacher"
  get 'rule_admin/:area', to: "rules#rule_admin"
  post '/update_rule_admin', to: "rules#update_rule_admin"
  get '/activities_admin/:id', to: "teachers#activities_admin"
  get '/activity_teacher_admin/:id/:origin', to: "teachers#activity_teacher_admin"
  get '/update_teacher_activity_admin/:id/:status/:origin', to: "teachers#update_teacher_activity_admin"

  get 'index_teacher', to: "activities#index_teacher"
  get 'new_teacher', to: "activities#new_teacher"
  post '/create_activity_teacher', to: "activities#create_activity_teacher"
  get 'destroy_activity_teacher/:id_activity', to: "activities#destroy_activity_teacher"
  get 'show_teacher_activity/:id_activity', to: "activities#show_teacher_activity"
  get 'edit_teacher_activity/:id_activity', to: "activities#edit_teacher_activity"
  post '/update_teacher_activity', to: "activities#update_teacher_activity"


  get 'index_teacher_rules', to: "rules#index_teacher_rules"
  get 'edit_rules_teacher/:area', to: "rules#edit_rules_teacher"
  post '/update_rule_teacher', to: "rules#update_rule_teacher"


  get '/internal_admin_information/:id', to: "internal#internal_admin_information"
  get '/internal_student_information/:id', to: "internal#internal_student_information"
  get '/internal_teacher_information/:id', to: "internal#internal_teacher_information"
  post '/update_admin', to: "internal#update_admin_attributes"
  post '/update_admin_password', to: "internal#update_admin_attributes_password"
  get '/update_admin', to: "internal#update_admin_attributes"
  get 'update_admin_password', to: "internal#update_admin_attributes_password"

  post '/update_student', to: "internal#update_student"
  post '/update_student_password', to: "internal#update_student_password"

  post '/update_teacher', to: "internal#update_teacher"
  post '/update_teacher_password', to: "internal#update_teacher_password"

  get 'list_students_requets', to: "teachers#list_students_requets"
  get 'show_student_thesis/:id_thesis', to: "thesis#show_student_thesis"

  get 'teacher_response_thesis/:id_thesis/:response', to: "thesis#teacher_response_thesis"
  get 'show_title_message/:id_title', to: "thesis#show_title_message"
  get 'show_approach_message/:id_approach', to: "thesis#show_approach_message"
  get 'show_general_purpose_message/:id_general_approach', to: "thesis#show_general_purpose_message"
  get 'show_specific_purposes_message/:version', to: "thesis#show_specific_purposes_message"

  get 'students_teacher_list', to: "students#students_teacher_list"
  get 'show_thesis_student/:id_student', to: "students#show_thesis_student"

  get 'show_title_detail/:id_thesis', to: "thesis#show_title_detail"
  get 'show_approach_detail/:id_thesis', to: "thesis#show_approach_detail"
  get 'show_general_purpose_detail/:id_thesis', to: "thesis#show_general_purpose_detail"
  get 'show_specific_purposes_detail/:id_thesis', to: "thesis#show_specific_purposes_detail"

  get 'show_title_teacher/:title_id', to: "thesis#show_title_teacher"
  get 'evaluate_title/:title_id', to: "thesis#evaluate_title"
  post '/title_teacher_evaluation', to: "thesis#title_teacher_evaluation"
  get 'confirm_title_teacher_evaluation/:title_id', to: "thesis#confirm_title_teacher_evaluation"
  post '/confirm_title_teacher_submit_evaluation', to: "thesis#confirm_title_teacher_submit_evaluation"

  get 'show_approach_teacher/:approach_id', to: "thesis#show_approach_teacher"
  get 'evaluate_approach/:approach_id', to: "thesis#evaluate_approach"
  post '/approach_teacher_evaluation', to: "thesis#approach_teacher_evaluation"
  get 'confirm_approach_teacher_evaluation/:approach_id', to: "thesis#confirm_approach_teacher_evaluation"
  post '/confirm_approach_teacher_submit_evaluation', to: "thesis#confirm_approach_teacher_submit_evaluation"

  get 'show_general_purpose_teacher/:general_purpose_id', to: "thesis#show_general_purpose_teacher"
  get 'evaluate_general_purpose/:general_purpose_id', to: "thesis#evaluate_general_purpose"
  post '/general_purpose_teacher_evaluation', to: "thesis#general_purpose_teacher_evaluation"
  get 'confirm_general_purpose_teacher_evaluation/:general_purpose_id', to: "thesis#confirm_general_purpose_teacher_evaluation"
  post '/confirm_general_purpose_teacher_submit_evaluation', to: "thesis#confirm_general_purpose_teacher_submit_evaluation"

  get 'show_specific_purpose_teacher/:version', to: "thesis#show_specific_purpose_teacher"
  get 'evaluate_specific_purpose/:version', to: "thesis#evaluate_specific_purpose"
  post '/specific_purpose_teacher_evaluation', to: "thesis#specific_purpose_teacher_evaluation"
  get 'confirm_specific_purpose_teacher_evaluation/:version', to: "thesis#confirm_specific_purpose_teacher_evaluation"
  post '/confirm_specific_purpose_teacher_submit_evaluation', to: "thesis#confirm_specific_purpose_teacher_submit_evaluation"


  root 'sessions#new'

  #sessions controller routes

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/unathorized', to: 'sessions#unathorized'
  post '/unathorized', to: 'sessions#unathorized'

  #password reset controller routes

  resources :password_resets, only: [:new, :create, :edit, :update]
  post '/password_resets/:id', to: 'password_resets#change_password'

app/models/rule.rb
class Rule < ApplicationRecord

  enum area: [:Titulo, :Planteamiento, :Obj_General, :Obj_Especifico]

end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/create.html.erb
<h1>Rules#create</h1>
<p>Find me in app/views/rules/create.html.erb</p>

app/views/rules/destroy.html.erb
<h1>Rules#destroy</h1>
<p>Find me in app/views/rules/destroy.html.erb</p>

app/views/rules/edit.html.erb
<h1>Rules#edit</h1>
<p>Find me in app/views/rules/edit.html.erb</p>

app/views/rules/edit_rules_teacher.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<script>

    function deleteRow(row) {

        var value = parseInt(document.getElementById('keyword_counter').value);

        var i = row.parentNode.parentNode.rowIndex;
        document.getElementById('KeywordsTabla').deleteRow(i);

        value = value - 1;
        document.getElementById('keyword_counter').value = value

        var x = document.getElementById('KeywordsTabla');
        var len = x.rows.length;

        document.getElementById('rule_keywords').value = ""

        for (var index = 1; index < len; index++) {

            var row = x.rows[index]

            if (document.getElementById('rule_keywords').value == "") {

                document.getElementById('rule_keywords').value = row.cells[0].getElementsByTagName('input')[0].value

            } else {

                document.getElementById('rule_keywords').value = document.getElementById('rule_keywords').value + "*" + row.cells[0].getElementsByTagName('input')[0].value

            }


        }


    }


    function insRow(respuesta) {

        var x = document.getElementById('KeywordsTabla');
        var value = parseInt(document.getElementById('keyword_counter').value);

        if (respuesta != "") {


            var new_row = x.rows[1].cloneNode(true);
            var len = x.rows.length;

            var inp1 = new_row.cells[0].getElementsByTagName('input')[0];
            inp1.id += len;
            inp1.value = respuesta;
            x.appendChild(new_row);

            if (value == 0) {

                document.getElementById('KeywordsTabla').deleteRow(1);

            }

            document.getElementById('rule_keywords').value = ""
            document.getElementById('keyword_text').value = ""

            value = value + 1;
            document.getElementById('keyword_counter').value = value


            for (var index = 1; index <= len; index++) {

                var row = x.rows[index]

                if (document.getElementById('rule_keywords').value == "") {

                    document.getElementById('rule_keywords').value = row.cells[0].getElementsByTagName('input')[0].value

                } else {

                    document.getElementById('rule_keywords').value = document.getElementById('rule_keywords').value + "*" + row.cells[0].getElementsByTagName('input')[0].value

                }


            }



        } else {

            alert("Debe introducir un texto para la palabra");

        }


    }

</script>

<% provide(:title, "Regla") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Consultar Regla</h1>


<%= form_for(:rule, url: update_rule_teacher_path) do |f| %>

  <%= render 'shared/error_rule_messages' %>

  <table>
    <tr>
      <td>Area</td>
      <td><%= @area %> </td>
    </tr>

    <tr>
      <td><%= f.label "Longuitud" %></td>
      <td><%= f.text_field :lenght %></td>
    </tr>

    <tr>
      <td><br></td>
    </tr>

    <tr>
      <td><h3>Palabras Asociadas</h3></td>
    </tr>

    <input type="hidden" name="keyword[counter]" id="keyword_counter" value="<%= @keywords.count %>>">
    <%= f.hidden_field :keywords, :value => @valueK %>



    <tr>
      <td><label>Palabra</label></td>
      <td><input type="text" name="keyword[text]" id="keyword_text"></td>
    </tr>

    <tr>
      <td>
        <input value="Agregar Palabra" class="btn btn-primary" data-disable-with="Agregar Palabra" onclick="insRow(document.getElementById('keyword_text').value)">
      </td>
    </tr>


    <%= f.hidden_field :area_value, :value => @areasValue %>
    <%= f.hidden_field :created_by, :value => session[:user_id] %>
    <%= f.hidden_field :user_type, :value => 2 %>

    <%= @valueK %>

    <tr>
      <td><br></td>
    </tr>
    <tr>
      <td><br></td>
    </tr>

    <tr>
      <table id="KeywordsTabla" border="1">
        <tr style="border: black 2px solid; height: 40px;">
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff">Palabras</b></td>
        </tr>
        <% if (@valueK == "") %>
          <tr>
            <td><input size=25 type="text" id="latbox"/></td>
            <td><input type="button" id="delPOIbutton" value="Eliminar" onclick="deleteRow(this)"/></td>
          </tr>
        <% else %>
          <% @keywordSplit = @valueK.split("*") %>
          <% @keywordSplit.each do |keyword| %>
            <tr>
              <td><input size=25 type="text" id="latbox" value="<%= keyword %>"/></td>
              <td>
                <input type="button" id="delPOIbutton" value="Eliminar" class="btn btn-danger" onclick="deleteRow(this)"/>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </tr>

    <tr>
      <td><br></td>
    </tr>
    <tr>
      <td><br></td>
    </tr>

    <tr>
      <td><%= f.submit "Actualizar Regla", class: "btn btn-primary" %></td>
    </tr>

  </table>
<% end %>

app/views/rules/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Reglas") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Reglas de Coordinación</h1>

<table>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Consultar Reglas para Título", {:controller => :rules, :action => :rule_admin, :area => 0}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Consultar Reglas para Planteamiento", {:controller => :rules, :action => :rule_admin, :area => 1}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Consultar Reglas para Objetivo General", {:controller => :rules, :action => :rule_admin, :area => 2}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Consultar Reglas para Objetivos Específicos", {:controller => :rules, :action => :rule_admin, :area => 3}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
</table>

<br><br>

<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Reglas de Profesores</h1>

<% if @rules.count != 0 %>

  <%= will_paginate @rules %>

  <table>

    <tr style="border: black 2px solid; height: 40px;">
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Área</b></th>
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
        <b style="color: #ffffff">Creada por</b></th>
      <th style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;"></th>
    </tr>
    <% @rules.each do |rule| %>

      <% if rule.user_type == 2 %>

        <%= @value = "" %>

        <% if rule.area == "Titulo"
             @value = "Título"
           elsif rule.area == "Planteamiento"
             @value = "Planteamiento del Problema"
           elsif rule.area == "Obj_General"
             @value = "Objetivo General"
           else
             @value = "Objetivos Específicos"
           end %>

        <tr style="border: black 2px solid; height: 40px;text-align: center;">
          <td style="border: black 1px solid"><%= @value %> </td>


          <% @teachers.each do |teacher| %>

            <% if rule.created_by == teacher.id %>

              <td style="border: black 1px solid"> <%= teacher.first_name %> <%= teacher.last_name %></td>
              <td style="border: black 1px solid"><%= link_to "Consultar", {:controller => :rules, :action => :rule_teacher, :id => rule.id}, {:class => 'btn btn-info', :style => 'width:100px;'} %></td>

              <% break %>

            <% end %>

          <% end %>

      <% end %>


      </tr>


    <% end %>

  </table>


  <%= will_paginate @rules %>

<% end %>

app/views/rules/index_teacher_rules.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>


<% provide(:title, "Reglas") %>
<h1 style="text-align: left; text-decoration: underline; text-decoration-color: #5981b8;">Reglas para sus Aspirantes a
  Tesistas</h1>

<table>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Reglas para Título", {:controller => :rules, :action => :edit_rules_teacher, :area => 0}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Reglas para Planteamiento", {:controller => :rules, :action => :edit_rules_teacher, :area => 1}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Reglas para Objetivo General", {:controller => :rules, :action => :edit_rules_teacher, :area => 2}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
  <tr style="height: 50px;text-align: center;">
    <th><%= link_to "Reglas para Objetivos Específicos", {:controller => :rules, :action => :edit_rules_teacher, :area => 3}, {:class => 'btn btn-success', :style => 'width:300px;'} %></th>
  </tr>
</table>

<br><br>

app/views/rules/new.html.erb
<h1>Rules#new</h1>
<p>Find me in app/views/rules/new.html.erb</p>

app/views/rules/rule_admin.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<script>

    function deleteRow(row) {

        var value = parseInt(document.getElementById('keyword_counter').value);

        var i = row.parentNode.parentNode.rowIndex;
        document.getElementById('KeywordsTabla').deleteRow(i);

        value = value - 1;
        document.getElementById('keyword_counter').value = value

        var x = document.getElementById('KeywordsTabla');
        var len = x.rows.length;

        document.getElementById('rule_keywords').value = ""

        for (var index = 1; index <= len; index++) {

            var row = x.rows[index]

            if (document.getElementById('rule_keywords').value == "") {

                document.getElementById('rule_keywords').value = row.cells[0].getElementsByTagName('input')[0].value

            } else {

                document.getElementById('rule_keywords').value = document.getElementById('activity_answers').value + "*" + row.cells[0].getElementsByTagName('input')[0].value + "%" + row.cells[1].getElementsByTagName('input')[0].value

            }


        }


    }


    function insRow(respuesta) {

        var x = document.getElementById('KeywordsTabla');
        var value = parseInt(document.getElementById('keyword_counter').value);

        if (respuesta != "") {


            var new_row = x.rows[1].cloneNode(true);
            var len = x.rows.length;

            var inp1 = new_row.cells[0].getElementsByTagName('input')[0];
            inp1.id += len;
            inp1.value = respuesta;
            x.appendChild(new_row);

            if (value == 0) {
                document.getElementById('KeywordsTabla').deleteRow(1);

            }

            document.getElementById('keyword_text').value = ""

            if (document.getElementById('rule_keywords').value == "") {

                document.getElementById('rule_keywords').value = respuesta;

            } else {

                document.getElementById('rule_keywords').value = document.getElementById('rule_keywords').value + "*" + respuesta;

            }

            value = value + 1;
            document.getElementById('keyword_counter').value = value

        } else {

            alert("Debe introducir un texto para la palabra");

        }


    }

</script>

<% provide(:title, "Regla") %>
<h1>Consultar Regla</h1>


<%= form_for(:rule, url: update_rule_admin_path) do |f| %>

  <%= render 'shared/error_rule_messages' %>

  <table>
    <tr>
      <td>Area</td>
      <td><%= @area %> </td>
    </tr>

    <tr>
      <td><%= f.label "Longuitud" %></td>
      <td><%= f.text_field :lenght %></td>
    </tr>

    <tr>
      <td><br></td>
    </tr>

    <tr>
      <td><h3>Palabras Asociadas</h3></td>
    </tr>

    <% if (@keywords.count == 0) %>

      <input type="hidden" name="keyword[counter]" id="keyword_counter" value="0">
      <%= f.hidden_field :keywords, :value => "" %>

    <% else %>

      <input type="hidden" name="keyword[counter]" id="keyword_counter" value="<%= @keywords.count %>>">
      <% @valueK = "" %>
      <% @keywords.each do |keyword| %>

        <% if @valueK == "" %>
          <% @valueK = keyword.word %>
        <% else %>
          <% @valueK = @valueK + "*" + keyword.word %>
        <% end %>

      <% end %>

      <%= f.hidden_field :keywords, :value => @valueK %>

    <% end %>



    <tr>
      <td><label>Palabra</label></td>
      <td><input type="text" name="keyword[text]" id="keyword_text"></td>
    </tr>

    <tr>
      <td>
        <input value="Agregar Palabra" class="btn btn-primary" data-disable-with="Agregar Palabra" onclick="insRow(document.getElementById('keyword_text').value)">
      </td>
    </tr>


    <%= f.hidden_field :area_value, :value => @areasValue %>
    <%= f.hidden_field :created_by, :value => session[:user_id] %>
    <%= f.hidden_field :user_type, :value => 3 %>

    <tr>
      <td><br></td>
    </tr>
    <tr>
      <td><br></td>
    </tr>

    <tr>
      <table id="KeywordsTabla" border="1">
        <tr style="border: black 2px solid; height: 40px;">
          <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
            <b style="color: #ffffff">Palabras</b></td>
        </tr>
        <% if (@keywords.count == 0) %>
          <tr>
            <td><input size=25 type="text" id="latbox"/></td>
            <td><input type="button" id="delPOIbutton" value="Eliminar" onclick="deleteRow(this)"/></td>
          </tr>
        <% else %>
          <% @keywords.each do |keyword| %>
            <tr>
              <td><input size=25 type="text" id="latbox" value="<%= keyword.word %>"/></td>
              <td><input type="button" id="delPOIbutton" value="Eliminar" class="btn btn-danger" onclick="deleteRow(this)"/></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </tr>

    <tr>
      <td><br></td>
    </tr>
    <tr>
      <td><br></td>
    </tr>

    <tr>
      <td><%= f.submit "Actualizar Regla", class: "btn btn-primary" %></td>
    </tr>

  </table>
<% end %>

app/views/rules/rule_teacher.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<% provide(:title, "Regla de Profesor") %>
<h1>Regla propuesta por Profesor para sus Tesistas</h1>

<table>

  <tr>
    <td style="width: 200px;">Área</td>

    <%= @value = "" %>

    <% if @rule.area == "Titulo"
         @value = "Título"
       elsif @rule.area == "Planteamiento"
         @value = "Planteamiento del Problema"
       elsif @rule.area == "Obj_General"
         @value = "Objetivo General"
       else
         @value = "Objetivos Específicos"
       end %>

    <td><%= @value %> </td>
  </tr>
  <tr style="width: 200px;">
    <td>Cantidad de carácteres</td>

    <td><%= @rule.lenght %> </td>
  </tr>

  <tr>
    <td><h3>Palabras</h3></td>
  </tr>

</table>

<%= will_paginate @keywords %>

<table border="1">
  <tr style="border: black 2px solid; height: 40px;">
    <td style="border: black 1px solid; text-align: center; background: #5981B8; width: 200px;">
      <b style="color: #ffffff">Palabras</b></td>
  </tr>
  <% @keywords.each do |keyword| %>
    <tr>
      <td><%= keyword.word %></td>
    </tr>
  <% end %>
</table>

<br>

app/views/rules/show.html.erb
<h1>Rules#show</h1>
<p>Find me in app/views/rules/show.html.erb</p>

app/views/rules/update.html.erb
<h1>Rules#update</h1>
<p>Find me in app/views/rules/update.html.erb</p>